template: external-bridged-provider
provider: cockroach
organization: pulumiverse
major-version: 0
providerDefaultBranch: main
upstreamProviderOrg: cockroachdb
publishRegistry: false
plugins:
  - name: terraform
    version: "1.0.19"
    kind: converter
languages:
  - dotnet
  - go
  - nodejs
  - python
publish:
  sdk: "all,!java"
  cdn: false
license:
  ignore:
    # Don't check for the license of the local shim package
    - github.com/cockroachdb/terraform-provider-cockroach/shim
toolVersions:
  go: "1.22.x"
pulumiConvert: 1
