// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Cockroach.Inputs
{

    public sealed class ClusterServerlessGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("routingId")]
        public Input<string>? RoutingId { get; set; }

        /// <summary>
        /// Spend limit in US cents.
        /// </summary>
        [Input("spendLimit")]
        public Input<int>? SpendLimit { get; set; }

        [Input("usageLimits")]
        public Input<Inputs.ClusterServerlessUsageLimitsGetArgs>? UsageLimits { get; set; }

        public ClusterServerlessGetArgs()
        {
        }
        public static new ClusterServerlessGetArgs Empty => new ClusterServerlessGetArgs();
    }
}
