// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Cockroach.Inputs
{

    public sealed class CmekRegionArgs : global::Pulumi.ResourceArgs
    {
        [Input("key", required: true)]
        public Input<Inputs.CmekRegionKeyArgs> Key { get; set; } = null!;

        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        [Input("status")]
        public Input<string>? Status { get; set; }

        public CmekRegionArgs()
        {
        }
        public static new CmekRegionArgs Empty => new CmekRegionArgs();
    }
}
