// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cockroach
{
    /// <summary>
    /// The provider type for the cockroach package. By default, resources use package-wide configuration
    /// settings, however an explicit `Provider` instance may be created and passed during resource
    /// construction to achieve fine-grained programmatic control over provider settings. See the
    /// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
    /// </summary>
    [CockroachResourceType("pulumi:providers:cockroach")]
    public partial class Provider : global::Pulumi.ProviderResource
    {
        /// <summary>
        /// The JWT from a JWT Issuer configured for the CockroachDB Cloud Organization. In this case, the vanity name of the
        /// organization is required and can be provided using the `COCKROACH_VANITY_NAME` environment variable. If the JWT is
        /// mapped to multiple identities, the identity to impersonate should be provided using the `COCKROACH_USERNAME` environment
        /// variable, and should contain either a user email address or a service account ID.
        /// </summary>
        [Output("apijwt")]
        public Output<string?> Apijwt { get; private set; } = null!;

        /// <summary>
        /// The API key to access CockroachDB Cloud. If this field is provided, it is used and `apijwt` is ignored.
        /// </summary>
        [Output("apikey")]
        public Output<string?> Apikey { get; private set; } = null!;


        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs? args = null, CustomResourceOptions? options = null)
            : base("cockroach", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
                AdditionalSecretOutputs =
                {
                    "apijwt",
                    "apikey",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("apijwt")]
        private Input<string>? _apijwt;

        /// <summary>
        /// The JWT from a JWT Issuer configured for the CockroachDB Cloud Organization. In this case, the vanity name of the
        /// organization is required and can be provided using the `COCKROACH_VANITY_NAME` environment variable. If the JWT is
        /// mapped to multiple identities, the identity to impersonate should be provided using the `COCKROACH_USERNAME` environment
        /// variable, and should contain either a user email address or a service account ID.
        /// </summary>
        public Input<string>? Apijwt
        {
            get => _apijwt;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _apijwt = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("apikey")]
        private Input<string>? _apikey;

        /// <summary>
        /// The API key to access CockroachDB Cloud. If this field is provided, it is used and `apijwt` is ignored.
        /// </summary>
        public Input<string>? Apikey
        {
            get => _apikey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _apikey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public ProviderArgs()
        {
        }
        public static new ProviderArgs Empty => new ProviderArgs();
    }
}
