// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Cockroach
{
    /// <summary>
    /// Utility resource that represents the one-time action of finalizing a cluster's pending CockroachDB version upgrade.
    /// </summary>
    [CockroachResourceType("cockroach:index/finalizeVersionUpgrade:FinalizeVersionUpgrade")]
    public partial class FinalizeVersionUpgrade : global::Pulumi.CustomResource
    {
        [Output("cockroachVersion")]
        public Output<string> CockroachVersion { get; private set; } = null!;


        /// <summary>
        /// Create a FinalizeVersionUpgrade resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public FinalizeVersionUpgrade(string name, FinalizeVersionUpgradeArgs args, CustomResourceOptions? options = null)
            : base("cockroach:index/finalizeVersionUpgrade:FinalizeVersionUpgrade", name, args ?? new FinalizeVersionUpgradeArgs(), MakeResourceOptions(options, ""))
        {
        }

        private FinalizeVersionUpgrade(string name, Input<string> id, FinalizeVersionUpgradeState? state = null, CustomResourceOptions? options = null)
            : base("cockroach:index/finalizeVersionUpgrade:FinalizeVersionUpgrade", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/lbrlabs",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing FinalizeVersionUpgrade resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static FinalizeVersionUpgrade Get(string name, Input<string> id, FinalizeVersionUpgradeState? state = null, CustomResourceOptions? options = null)
        {
            return new FinalizeVersionUpgrade(name, id, state, options);
        }
    }

    public sealed class FinalizeVersionUpgradeArgs : global::Pulumi.ResourceArgs
    {
        [Input("cockroachVersion", required: true)]
        public Input<string> CockroachVersion { get; set; } = null!;

        public FinalizeVersionUpgradeArgs()
        {
        }
        public static new FinalizeVersionUpgradeArgs Empty => new FinalizeVersionUpgradeArgs();
    }

    public sealed class FinalizeVersionUpgradeState : global::Pulumi.ResourceArgs
    {
        [Input("cockroachVersion")]
        public Input<string>? CockroachVersion { get; set; }

        public FinalizeVersionUpgradeState()
        {
        }
        public static new FinalizeVersionUpgradeState Empty => new FinalizeVersionUpgradeState();
    }
}
