// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Cockroach
{
    public static class GetCockroachCluster
    {
        /// <summary>
        /// Cluster Data Source
        /// </summary>
        public static Task<GetCockroachClusterResult> InvokeAsync(GetCockroachClusterArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCockroachClusterResult>("cockroach:index/getCockroachCluster:getCockroachCluster", args ?? new GetCockroachClusterArgs(), options.WithDefaults());

        /// <summary>
        /// Cluster Data Source
        /// </summary>
        public static Output<GetCockroachClusterResult> Invoke(GetCockroachClusterInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetCockroachClusterResult>("cockroach:index/getCockroachCluster:getCockroachCluster", args ?? new GetCockroachClusterInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetCockroachClusterArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetCockroachClusterArgs()
        {
        }
        public static new GetCockroachClusterArgs Empty => new GetCockroachClusterArgs();
    }

    public sealed class GetCockroachClusterInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetCockroachClusterInvokeArgs()
        {
        }
        public static new GetCockroachClusterInvokeArgs Empty => new GetCockroachClusterInvokeArgs();
    }


    [OutputType]
    public sealed class GetCockroachClusterResult
    {
        public readonly string AccountId;
        public readonly string CloudProvider;
        public readonly string CockroachVersion;
        public readonly string CreatorId;
        public readonly Outputs.GetCockroachClusterDedicatedResult Dedicated;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Name of cluster
        /// </summary>
        public readonly string Name;
        public readonly string OperationStatus;
        public readonly string Plan;
        public readonly ImmutableArray<Outputs.GetCockroachClusterRegionResult> Regions;
        public readonly Outputs.GetCockroachClusterServerlessResult Serverless;
        public readonly string State;
        public readonly string UpgradeStatus;

        [OutputConstructor]
        private GetCockroachClusterResult(
            string accountId,

            string cloudProvider,

            string cockroachVersion,

            string creatorId,

            Outputs.GetCockroachClusterDedicatedResult dedicated,

            string id,

            string name,

            string operationStatus,

            string plan,

            ImmutableArray<Outputs.GetCockroachClusterRegionResult> regions,

            Outputs.GetCockroachClusterServerlessResult serverless,

            string state,

            string upgradeStatus)
        {
            AccountId = accountId;
            CloudProvider = cloudProvider;
            CockroachVersion = cockroachVersion;
            CreatorId = creatorId;
            Dedicated = dedicated;
            Id = id;
            Name = name;
            OperationStatus = operationStatus;
            Plan = plan;
            Regions = regions;
            Serverless = serverless;
            State = state;
            UpgradeStatus = upgradeStatus;
        }
    }
}
