// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/pulumiverse/pulumi-cockroach/sdk/go/cockroach/internal"
)

var _ = internal.GetEnvOrDefault

// The JWT from a JWT Issuer configured for the CockroachDB Cloud Organization. In this case, the vanity name of the
// organization is required and can be provided using the `COCKROACH_VANITY_NAME` environment variable. If the JWT is
// mapped to multiple identities, the identity to impersonate should be provided using the `COCKROACH_USERNAME` environment
// variable, and should contain either a user email address or a service account ID.
func GetApijwt(ctx *pulumi.Context) string {
	return config.Get(ctx, "cockroach:apijwt")
}

// The API key to access CockroachDB Cloud. If this field is provided, it is used and `apijwt` is ignored.
func GetApikey(ctx *pulumi.Context) string {
	return config.Get(ctx, "cockroach:apikey")
}
