// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cockroach;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AllowListArgs extends com.pulumi.resources.ResourceArgs {

    public static final AllowListArgs Empty = new AllowListArgs();

    @Import(name="cidrIp", required=true)
    private Output<String> cidrIp;

    public Output<String> cidrIp() {
        return this.cidrIp;
    }

    @Import(name="cidrMask", required=true)
    private Output<Integer> cidrMask;

    public Output<Integer> cidrMask() {
        return this.cidrMask;
    }

    @Import(name="clusterId", required=true)
    private Output<String> clusterId;

    public Output<String> clusterId() {
        return this.clusterId;
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="sql", required=true)
    private Output<Boolean> sql;

    public Output<Boolean> sql() {
        return this.sql;
    }

    @Import(name="ui", required=true)
    private Output<Boolean> ui;

    public Output<Boolean> ui() {
        return this.ui;
    }

    private AllowListArgs() {}

    private AllowListArgs(AllowListArgs $) {
        this.cidrIp = $.cidrIp;
        this.cidrMask = $.cidrMask;
        this.clusterId = $.clusterId;
        this.name = $.name;
        this.sql = $.sql;
        this.ui = $.ui;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AllowListArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AllowListArgs $;

        public Builder() {
            $ = new AllowListArgs();
        }

        public Builder(AllowListArgs defaults) {
            $ = new AllowListArgs(Objects.requireNonNull(defaults));
        }

        public Builder cidrIp(Output<String> cidrIp) {
            $.cidrIp = cidrIp;
            return this;
        }

        public Builder cidrIp(String cidrIp) {
            return cidrIp(Output.of(cidrIp));
        }

        public Builder cidrMask(Output<Integer> cidrMask) {
            $.cidrMask = cidrMask;
            return this;
        }

        public Builder cidrMask(Integer cidrMask) {
            return cidrMask(Output.of(cidrMask));
        }

        public Builder clusterId(Output<String> clusterId) {
            $.clusterId = clusterId;
            return this;
        }

        public Builder clusterId(String clusterId) {
            return clusterId(Output.of(clusterId));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder sql(Output<Boolean> sql) {
            $.sql = sql;
            return this;
        }

        public Builder sql(Boolean sql) {
            return sql(Output.of(sql));
        }

        public Builder ui(Output<Boolean> ui) {
            $.ui = ui;
            return this;
        }

        public Builder ui(Boolean ui) {
            return ui(Output.of(ui));
        }

        public AllowListArgs build() {
            $.cidrIp = Objects.requireNonNull($.cidrIp, "expected parameter 'cidrIp' to be non-null");
            $.cidrMask = Objects.requireNonNull($.cidrMask, "expected parameter 'cidrMask' to be non-null");
            $.clusterId = Objects.requireNonNull($.clusterId, "expected parameter 'clusterId' to be non-null");
            $.sql = Objects.requireNonNull($.sql, "expected parameter 'sql' to be non-null");
            $.ui = Objects.requireNonNull($.ui, "expected parameter 'ui' to be non-null");
            return $;
        }
    }

}
