// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cockroach;

import com.pulumi.cockroach.CaCertArgs;
import com.pulumi.cockroach.Utilities;
import com.pulumi.cockroach.inputs.CaCertState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * Manages client CA certs.
 * 
 */
@ResourceType(type="cockroach:index/caCert:CaCert")
public class CaCert extends com.pulumi.resources.CustomResource {
    /**
     * Cluster ID.
     * 
     */
    @Export(name="clusterId", type=String.class, parameters={})
    private Output<String> clusterId;

    /**
     * @return Cluster ID.
     * 
     */
    public Output<String> clusterId() {
        return this.clusterId;
    }
    /**
     * Status of client CA certs on a cluster.
     * 
     */
    @Export(name="status", type=String.class, parameters={})
    private Output<String> status;

    /**
     * @return Status of client CA certs on a cluster.
     * 
     */
    public Output<String> status() {
        return this.status;
    }
    /**
     * X509 certificate in PEM format.
     * 
     */
    @Export(name="x509PemCert", type=String.class, parameters={})
    private Output<String> x509PemCert;

    /**
     * @return X509 certificate in PEM format.
     * 
     */
    public Output<String> x509PemCert() {
        return this.x509PemCert;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public CaCert(String name) {
        this(name, CaCertArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public CaCert(String name, CaCertArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public CaCert(String name, CaCertArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cockroach:index/caCert:CaCert", name, args == null ? CaCertArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private CaCert(String name, Output<String> id, @Nullable CaCertState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cockroach:index/caCert:CaCert", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static CaCert get(String name, Output<String> id, @Nullable CaCertState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new CaCert(name, id, state, options);
    }
}
