// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cockroach;

import com.pulumi.cockroach.MetricExportDatadogConfigArgs;
import com.pulumi.cockroach.Utilities;
import com.pulumi.cockroach.inputs.MetricExportDatadogConfigState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

/**
 * DataDog metric export configuration for a cluster.
 * 
 */
@ResourceType(type="cockroach:index/metricExportDatadogConfig:MetricExportDatadogConfig")
public class MetricExportDatadogConfig extends com.pulumi.resources.CustomResource {
    /**
     * A Datadog API key.
     * 
     */
    @Export(name="apiKey", type=String.class, parameters={})
    private Output<String> apiKey;

    /**
     * @return A Datadog API key.
     * 
     */
    public Output<String> apiKey() {
        return this.apiKey;
    }
    /**
     * Cluster ID.
     * 
     */
    @Export(name="clusterId", type=String.class, parameters={})
    private Output<String> clusterId;

    /**
     * @return Cluster ID.
     * 
     */
    public Output<String> clusterId() {
        return this.clusterId;
    }
    /**
     * The Datadog region to export to.
     * 
     */
    @Export(name="site", type=String.class, parameters={})
    private Output<String> site;

    /**
     * @return The Datadog region to export to.
     * 
     */
    public Output<String> site() {
        return this.site;
    }
    /**
     * Encodes the possible states that a metric export configuration can be in as it is created, deployed, and disabled.
     * 
     */
    @Export(name="status", type=String.class, parameters={})
    private Output<String> status;

    /**
     * @return Encodes the possible states that a metric export configuration can be in as it is created, deployed, and disabled.
     * 
     */
    public Output<String> status() {
        return this.status;
    }
    /**
     * Elaborates on the metric export status and hints at how to fix issues that may have occurred during asynchronous operations.
     * 
     */
    @Export(name="userMessage", type=String.class, parameters={})
    private Output<String> userMessage;

    /**
     * @return Elaborates on the metric export status and hints at how to fix issues that may have occurred during asynchronous operations.
     * 
     */
    public Output<String> userMessage() {
        return this.userMessage;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public MetricExportDatadogConfig(String name) {
        this(name, MetricExportDatadogConfigArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public MetricExportDatadogConfig(String name, MetricExportDatadogConfigArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public MetricExportDatadogConfig(String name, MetricExportDatadogConfigArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cockroach:index/metricExportDatadogConfig:MetricExportDatadogConfig", name, args == null ? MetricExportDatadogConfigArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private MetricExportDatadogConfig(String name, Output<String> id, @Nullable MetricExportDatadogConfigState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cockroach:index/metricExportDatadogConfig:MetricExportDatadogConfig", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "apiKey"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static MetricExportDatadogConfig get(String name, Output<String> id, @Nullable MetricExportDatadogConfigState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new MetricExportDatadogConfig(name, id, state, options);
    }
}
