// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cockroach;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class PrivateEndpointTrustedOwnerArgs extends com.pulumi.resources.ResourceArgs {

    public static final PrivateEndpointTrustedOwnerArgs Empty = new PrivateEndpointTrustedOwnerArgs();

    /**
     * UUID of the cluster the private endpoint trusted owner entry belongs to.
     * 
     */
    @Import(name="clusterId", required=true)
    private Output<String> clusterId;

    /**
     * @return UUID of the cluster the private endpoint trusted owner entry belongs to.
     * 
     */
    public Output<String> clusterId() {
        return this.clusterId;
    }

    /**
     * Owner ID of the private endpoint connection in the cloud provider.
     * 
     */
    @Import(name="externalOwnerId", required=true)
    private Output<String> externalOwnerId;

    /**
     * @return Owner ID of the private endpoint connection in the cloud provider.
     * 
     */
    public Output<String> externalOwnerId() {
        return this.externalOwnerId;
    }

    /**
     * Representation of the external_owner_id field. Allowed values are: * AWS_ACCOUNT_ID
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return Representation of the external_owner_id field. Allowed values are: * AWS_ACCOUNT_ID
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    private PrivateEndpointTrustedOwnerArgs() {}

    private PrivateEndpointTrustedOwnerArgs(PrivateEndpointTrustedOwnerArgs $) {
        this.clusterId = $.clusterId;
        this.externalOwnerId = $.externalOwnerId;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PrivateEndpointTrustedOwnerArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PrivateEndpointTrustedOwnerArgs $;

        public Builder() {
            $ = new PrivateEndpointTrustedOwnerArgs();
        }

        public Builder(PrivateEndpointTrustedOwnerArgs defaults) {
            $ = new PrivateEndpointTrustedOwnerArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param clusterId UUID of the cluster the private endpoint trusted owner entry belongs to.
         * 
         * @return builder
         * 
         */
        public Builder clusterId(Output<String> clusterId) {
            $.clusterId = clusterId;
            return this;
        }

        /**
         * @param clusterId UUID of the cluster the private endpoint trusted owner entry belongs to.
         * 
         * @return builder
         * 
         */
        public Builder clusterId(String clusterId) {
            return clusterId(Output.of(clusterId));
        }

        /**
         * @param externalOwnerId Owner ID of the private endpoint connection in the cloud provider.
         * 
         * @return builder
         * 
         */
        public Builder externalOwnerId(Output<String> externalOwnerId) {
            $.externalOwnerId = externalOwnerId;
            return this;
        }

        /**
         * @param externalOwnerId Owner ID of the private endpoint connection in the cloud provider.
         * 
         * @return builder
         * 
         */
        public Builder externalOwnerId(String externalOwnerId) {
            return externalOwnerId(Output.of(externalOwnerId));
        }

        /**
         * @param type Representation of the external_owner_id field. Allowed values are: * AWS_ACCOUNT_ID
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type Representation of the external_owner_id field. Allowed values are: * AWS_ACCOUNT_ID
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public PrivateEndpointTrustedOwnerArgs build() {
            $.clusterId = Objects.requireNonNull($.clusterId, "expected parameter 'clusterId' to be non-null");
            $.externalOwnerId = Objects.requireNonNull($.externalOwnerId, "expected parameter 'externalOwnerId' to be non-null");
            $.type = Objects.requireNonNull($.type, "expected parameter 'type' to be non-null");
            return $;
        }
    }

}
