// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cockroach;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class PrivateEndpointServicesArgs extends com.pulumi.resources.ResourceArgs {

    public static final PrivateEndpointServicesArgs Empty = new PrivateEndpointServicesArgs();

    @Import(name="clusterId", required=true)
    private Output<String> clusterId;

    public Output<String> clusterId() {
        return this.clusterId;
    }

    private PrivateEndpointServicesArgs() {}

    private PrivateEndpointServicesArgs(PrivateEndpointServicesArgs $) {
        this.clusterId = $.clusterId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PrivateEndpointServicesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PrivateEndpointServicesArgs $;

        public Builder() {
            $ = new PrivateEndpointServicesArgs();
        }

        public Builder(PrivateEndpointServicesArgs defaults) {
            $ = new PrivateEndpointServicesArgs(Objects.requireNonNull(defaults));
        }

        public Builder clusterId(Output<String> clusterId) {
            $.clusterId = clusterId;
            return this;
        }

        public Builder clusterId(String clusterId) {
            return clusterId(Output.of(clusterId));
        }

        public PrivateEndpointServicesArgs build() {
            $.clusterId = Objects.requireNonNull($.clusterId, "expected parameter 'clusterId' to be non-null");
            return $;
        }
    }

}
