// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cockroach;

import com.pulumi.cockroach.SqlUserArgs;
import com.pulumi.cockroach.Utilities;
import com.pulumi.cockroach.inputs.SqlUserState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * CockroachDB SQL user.
 * 
 */
@ResourceType(type="cockroach:index/sqlUser:SqlUser")
public class SqlUser extends com.pulumi.resources.CustomResource {
    @Export(name="clusterId", type=String.class, parameters={})
    private Output<String> clusterId;

    public Output<String> clusterId() {
        return this.clusterId;
    }
    /**
     * SQL user name.
     * 
     */
    @Export(name="name", type=String.class, parameters={})
    private Output<String> name;

    /**
     * @return SQL user name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * If provided, this field sets the password of the SQL user when created. If omitted, a random password is generated, but
     * not saved to Terraform state. The password must be changed via the CockroachDB cloud console.
     * 
     */
    @Export(name="password", type=String.class, parameters={})
    private Output</* @Nullable */ String> password;

    /**
     * @return If provided, this field sets the password of the SQL user when created. If omitted, a random password is generated, but
     * not saved to Terraform state. The password must be changed via the CockroachDB cloud console.
     * 
     */
    public Output<Optional<String>> password() {
        return Codegen.optional(this.password);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public SqlUser(String name) {
        this(name, SqlUserArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public SqlUser(String name, SqlUserArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public SqlUser(String name, SqlUserArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cockroach:index/sqlUser:SqlUser", name, args == null ? SqlUserArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private SqlUser(String name, Output<String> id, @Nullable SqlUserState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cockroach:index/sqlUser:SqlUser", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "password"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static SqlUser get(String name, Output<String> id, @Nullable SqlUserState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new SqlUser(name, id, state, options);
    }
}
