// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Cockroach.Outputs
{

    [OutputType]
    public sealed class ApiOidcConfigIdentityMap
    {
        /// <summary>
        /// The username (email or service account id) of the CC user that the token should map to.
        /// </summary>
        public readonly string CcIdentity;
        /// <summary>
        /// Indicates that the token_principal field is a regex value.
        /// </summary>
        public readonly bool? IsRegex;
        /// <summary>
        /// The token value that needs to be mapped.
        /// </summary>
        public readonly string TokenIdentity;

        [OutputConstructor]
        private ApiOidcConfigIdentityMap(
            string ccIdentity,

            bool? isRegex,

            string tokenIdentity)
        {
            CcIdentity = ccIdentity;
            IsRegex = isRegex;
            TokenIdentity = tokenIdentity;
        }
    }
}
