// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Cockroach.Outputs
{

    [OutputType]
    public sealed class ClusterRegion
    {
        /// <summary>
        /// Name of cluster
        /// </summary>
        public readonly string Name;
        public readonly int? NodeCount;
        /// <summary>
        /// Set to true to mark this region as the primary for a Serverless cluster. Exactly one region must be primary. Dedicated clusters expect to have no primary region.
        /// </summary>
        public readonly bool? Primary;
        public readonly string? SqlDns;
        public readonly string? UiDns;

        [OutputConstructor]
        private ClusterRegion(
            string name,

            int? nodeCount,

            bool? primary,

            string? sqlDns,

            string? uiDns)
        {
            Name = name;
            NodeCount = nodeCount;
            Primary = primary;
            SqlDns = sqlDns;
            UiDns = uiDns;
        }
    }
}
