// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Cockroach.Outputs
{

    [OutputType]
    public sealed class GetCockroachClusterRegionResult
    {
        /// <summary>
        /// Name of cluster
        /// </summary>
        public readonly string Name;
        public readonly int NodeCount;
        public readonly bool Primary;
        public readonly string SqlDns;
        public readonly string UiDns;

        [OutputConstructor]
        private GetCockroachClusterRegionResult(
            string name,

            int nodeCount,

            bool primary,

            string sqlDns,

            string uiDns)
        {
            Name = name;
            NodeCount = nodeCount;
            Primary = primary;
            SqlDns = sqlDns;
            UiDns = uiDns;
        }
    }
}
