// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Cockroach.Outputs
{

    [OutputType]
    public sealed class GetCockroachClusterServerlessResult
    {
        public readonly string RoutingId;
        public readonly int SpendLimit;
        public readonly Outputs.GetCockroachClusterServerlessUsageLimitsResult UsageLimits;

        [OutputConstructor]
        private GetCockroachClusterServerlessResult(
            string routingId,

            int spendLimit,

            Outputs.GetCockroachClusterServerlessUsageLimitsResult usageLimits)
        {
            RoutingId = routingId;
            SpendLimit = spendLimit;
            UsageLimits = usageLimits;
        }
    }
}
