// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Cockroach.Outputs
{

    [OutputType]
    public sealed class PrivateEndpointServicesService
    {
        public readonly Outputs.PrivateEndpointServicesServiceAws? Aws;
        /// <summary>
        /// Cloud provider associated with this service.
        /// </summary>
        public readonly string? CloudProvider;
        /// <summary>
        /// Cloud provider region code associated with this service.
        /// </summary>
        public readonly string? RegionName;
        /// <summary>
        /// Operation status of the service.
        /// </summary>
        public readonly string? Status;

        [OutputConstructor]
        private PrivateEndpointServicesService(
            Outputs.PrivateEndpointServicesServiceAws? aws,

            string? cloudProvider,

            string? regionName,

            string? status)
        {
            Aws = aws;
            CloudProvider = cloudProvider;
            RegionName = regionName;
            Status = status;
        }
    }
}
