// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cockroach.Outputs
{

    [OutputType]
    public sealed class ClusterServerless
    {
        public readonly string? RoutingId;
        public readonly int? SpendLimit;
        public readonly Outputs.ClusterServerlessUsageLimits? UsageLimits;

        [OutputConstructor]
        private ClusterServerless(
            string? routingId,

            int? spendLimit,

            Outputs.ClusterServerlessUsageLimits? usageLimits)
        {
            RoutingId = routingId;
            SpendLimit = spendLimit;
            UsageLimits = usageLimits;
        }
    }
}
