// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cockroach.Outputs
{

    [OutputType]
    public sealed class GetConnectionStringConnectionParamsResult
    {
        /// <summary>
        /// Database value to use in a connection URL.
        /// </summary>
        public readonly string Database;
        /// <summary>
        /// Host value to use in a connection URL.
        /// </summary>
        public readonly string Host;
        /// <summary>
        /// Password value to use in a connection URL.
        /// </summary>
        public readonly string Password;
        /// <summary>
        /// Port value to use in a connection URL.
        /// </summary>
        public readonly string Port;
        /// <summary>
        /// Username value to use in a connection URL.
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private GetConnectionStringConnectionParamsResult(
            string database,

            string host,

            string password,

            string port,

            string username)
        {
            Database = database;
            Host = host;
            Password = password;
            Port = port;
            Username = username;
        }
    }
}
