// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cockroach.Outputs
{

    [OutputType]
    public sealed class GetCockroachClusterDedicatedResult
    {
        /// <summary>
        /// The IPv4 range in CIDR format that is in use by the cluster. It is only set on GCP clusters and is otherwise empty.
        /// </summary>
        public readonly string CidrRange;
        /// <summary>
        /// Number of disk I/O operations per second that are permitted on each node in the cluster. Zero indicates the cloud provider-specific default.
        /// </summary>
        public readonly int DiskIops;
        /// <summary>
        /// Machine type identifier within the given cloud provider, ex. m6.xlarge, n2-standard-4.
        /// </summary>
        public readonly string MachineType;
        /// <summary>
        /// Memory per node in GiB.
        /// </summary>
        public readonly double MemoryGib;
        /// <summary>
        /// Number of virtual CPUs per node in the cluster.
        /// </summary>
        public readonly int NumVirtualCpus;
        /// <summary>
        /// Indicates whether private IP addresses are assigned to nodes. Required for CMEK and other advanced networking features.
        /// </summary>
        public readonly bool PrivateNetworkVisibility;
        /// <summary>
        /// Storage amount per node in GiB.
        /// </summary>
        public readonly int StorageGib;

        [OutputConstructor]
        private GetCockroachClusterDedicatedResult(
            string cidrRange,

            int diskIops,

            string machineType,

            double memoryGib,

            int numVirtualCpus,

            bool privateNetworkVisibility,

            int storageGib)
        {
            CidrRange = cidrRange;
            DiskIops = diskIops;
            MachineType = machineType;
            MemoryGib = memoryGib;
            NumVirtualCpus = numVirtualCpus;
            PrivateNetworkVisibility = privateNetworkVisibility;
            StorageGib = storageGib;
        }
    }
}
