// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cockroach.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CmekAdditionalRegionArgs extends com.pulumi.resources.ResourceArgs {

    public static final CmekAdditionalRegionArgs Empty = new CmekAdditionalRegionArgs();

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    @Import(name="nodeCount")
    private @Nullable Output<Integer> nodeCount;

    public Optional<Output<Integer>> nodeCount() {
        return Optional.ofNullable(this.nodeCount);
    }

    /**
     * Set to true to mark this region as the primary for a Serverless cluster. Exactly one region must be primary. Dedicated clusters expect to have no primary region.
     * 
     */
    @Import(name="primary")
    private @Nullable Output<Boolean> primary;

    /**
     * @return Set to true to mark this region as the primary for a Serverless cluster. Exactly one region must be primary. Dedicated clusters expect to have no primary region.
     * 
     */
    public Optional<Output<Boolean>> primary() {
        return Optional.ofNullable(this.primary);
    }

    @Import(name="sqlDns")
    private @Nullable Output<String> sqlDns;

    public Optional<Output<String>> sqlDns() {
        return Optional.ofNullable(this.sqlDns);
    }

    @Import(name="uiDns")
    private @Nullable Output<String> uiDns;

    public Optional<Output<String>> uiDns() {
        return Optional.ofNullable(this.uiDns);
    }

    private CmekAdditionalRegionArgs() {}

    private CmekAdditionalRegionArgs(CmekAdditionalRegionArgs $) {
        this.name = $.name;
        this.nodeCount = $.nodeCount;
        this.primary = $.primary;
        this.sqlDns = $.sqlDns;
        this.uiDns = $.uiDns;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CmekAdditionalRegionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CmekAdditionalRegionArgs $;

        public Builder() {
            $ = new CmekAdditionalRegionArgs();
        }

        public Builder(CmekAdditionalRegionArgs defaults) {
            $ = new CmekAdditionalRegionArgs(Objects.requireNonNull(defaults));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder nodeCount(@Nullable Output<Integer> nodeCount) {
            $.nodeCount = nodeCount;
            return this;
        }

        public Builder nodeCount(Integer nodeCount) {
            return nodeCount(Output.of(nodeCount));
        }

        /**
         * @param primary Set to true to mark this region as the primary for a Serverless cluster. Exactly one region must be primary. Dedicated clusters expect to have no primary region.
         * 
         * @return builder
         * 
         */
        public Builder primary(@Nullable Output<Boolean> primary) {
            $.primary = primary;
            return this;
        }

        /**
         * @param primary Set to true to mark this region as the primary for a Serverless cluster. Exactly one region must be primary. Dedicated clusters expect to have no primary region.
         * 
         * @return builder
         * 
         */
        public Builder primary(Boolean primary) {
            return primary(Output.of(primary));
        }

        public Builder sqlDns(@Nullable Output<String> sqlDns) {
            $.sqlDns = sqlDns;
            return this;
        }

        public Builder sqlDns(String sqlDns) {
            return sqlDns(Output.of(sqlDns));
        }

        public Builder uiDns(@Nullable Output<String> uiDns) {
            $.uiDns = uiDns;
            return this;
        }

        public Builder uiDns(String uiDns) {
            return uiDns(Output.of(uiDns));
        }

        public CmekAdditionalRegionArgs build() {
            $.name = Objects.requireNonNull($.name, "expected parameter 'name' to be non-null");
            return $;
        }
    }

}
