// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cockroach.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class GetClusterCertPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetClusterCertPlainArgs Empty = new GetClusterCertPlainArgs();

    /**
     * Cluster ID.
     * 
     */
    @Import(name="id", required=true)
    private String id;

    /**
     * @return Cluster ID.
     * 
     */
    public String id() {
        return this.id;
    }

    private GetClusterCertPlainArgs() {}

    private GetClusterCertPlainArgs(GetClusterCertPlainArgs $) {
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetClusterCertPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetClusterCertPlainArgs $;

        public Builder() {
            $ = new GetClusterCertPlainArgs();
        }

        public Builder(GetClusterCertPlainArgs defaults) {
            $ = new GetClusterCertPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id Cluster ID.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            $.id = id;
            return this;
        }

        public GetClusterCertPlainArgs build() {
            $.id = Objects.requireNonNull($.id, "expected parameter 'id' to be non-null");
            return $;
        }
    }

}
