// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cockroach.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class LogExportConfigGroupArgs extends com.pulumi.resources.ResourceArgs {

    public static final LogExportConfigGroupArgs Empty = new LogExportConfigGroupArgs();

    @Import(name="channels", required=true)
    private Output<List<String>> channels;

    public Output<List<String>> channels() {
        return this.channels;
    }

    @Import(name="logName", required=true)
    private Output<String> logName;

    public Output<String> logName() {
        return this.logName;
    }

    @Import(name="minLevel")
    private @Nullable Output<String> minLevel;

    public Optional<Output<String>> minLevel() {
        return Optional.ofNullable(this.minLevel);
    }

    @Import(name="redact")
    private @Nullable Output<Boolean> redact;

    public Optional<Output<Boolean>> redact() {
        return Optional.ofNullable(this.redact);
    }

    private LogExportConfigGroupArgs() {}

    private LogExportConfigGroupArgs(LogExportConfigGroupArgs $) {
        this.channels = $.channels;
        this.logName = $.logName;
        this.minLevel = $.minLevel;
        this.redact = $.redact;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LogExportConfigGroupArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LogExportConfigGroupArgs $;

        public Builder() {
            $ = new LogExportConfigGroupArgs();
        }

        public Builder(LogExportConfigGroupArgs defaults) {
            $ = new LogExportConfigGroupArgs(Objects.requireNonNull(defaults));
        }

        public Builder channels(Output<List<String>> channels) {
            $.channels = channels;
            return this;
        }

        public Builder channels(List<String> channels) {
            return channels(Output.of(channels));
        }

        public Builder channels(String... channels) {
            return channels(List.of(channels));
        }

        public Builder logName(Output<String> logName) {
            $.logName = logName;
            return this;
        }

        public Builder logName(String logName) {
            return logName(Output.of(logName));
        }

        public Builder minLevel(@Nullable Output<String> minLevel) {
            $.minLevel = minLevel;
            return this;
        }

        public Builder minLevel(String minLevel) {
            return minLevel(Output.of(minLevel));
        }

        public Builder redact(@Nullable Output<Boolean> redact) {
            $.redact = redact;
            return this;
        }

        public Builder redact(Boolean redact) {
            return redact(Output.of(redact));
        }

        public LogExportConfigGroupArgs build() {
            $.channels = Objects.requireNonNull($.channels, "expected parameter 'channels' to be non-null");
            $.logName = Objects.requireNonNull($.logName, "expected parameter 'logName' to be non-null");
            return $;
        }
    }

}
