// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cockroach.inputs;

import com.pulumi.cockroach.inputs.UserRoleGrantsRoleArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class UserRoleGrantsState extends com.pulumi.resources.ResourceArgs {

    public static final UserRoleGrantsState Empty = new UserRoleGrantsState();

    @Import(name="roles")
    private @Nullable Output<List<UserRoleGrantsRoleArgs>> roles;

    public Optional<Output<List<UserRoleGrantsRoleArgs>>> roles() {
        return Optional.ofNullable(this.roles);
    }

    @Import(name="userId")
    private @Nullable Output<String> userId;

    public Optional<Output<String>> userId() {
        return Optional.ofNullable(this.userId);
    }

    private UserRoleGrantsState() {}

    private UserRoleGrantsState(UserRoleGrantsState $) {
        this.roles = $.roles;
        this.userId = $.userId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(UserRoleGrantsState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private UserRoleGrantsState $;

        public Builder() {
            $ = new UserRoleGrantsState();
        }

        public Builder(UserRoleGrantsState defaults) {
            $ = new UserRoleGrantsState(Objects.requireNonNull(defaults));
        }

        public Builder roles(@Nullable Output<List<UserRoleGrantsRoleArgs>> roles) {
            $.roles = roles;
            return this;
        }

        public Builder roles(List<UserRoleGrantsRoleArgs> roles) {
            return roles(Output.of(roles));
        }

        public Builder roles(UserRoleGrantsRoleArgs... roles) {
            return roles(List.of(roles));
        }

        public Builder userId(@Nullable Output<String> userId) {
            $.userId = userId;
            return this;
        }

        public Builder userId(String userId) {
            return userId(Output.of(userId));
        }

        public UserRoleGrantsState build() {
            return $;
        }
    }

}
