// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cockroach.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class LogExportConfigGroup {
    private List<String> channels;
    private String logName;
    private @Nullable String minLevel;
    private @Nullable Boolean redact;

    private LogExportConfigGroup() {}
    public List<String> channels() {
        return this.channels;
    }
    public String logName() {
        return this.logName;
    }
    public Optional<String> minLevel() {
        return Optional.ofNullable(this.minLevel);
    }
    public Optional<Boolean> redact() {
        return Optional.ofNullable(this.redact);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LogExportConfigGroup defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> channels;
        private String logName;
        private @Nullable String minLevel;
        private @Nullable Boolean redact;
        public Builder() {}
        public Builder(LogExportConfigGroup defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.channels = defaults.channels;
    	      this.logName = defaults.logName;
    	      this.minLevel = defaults.minLevel;
    	      this.redact = defaults.redact;
        }

        @CustomType.Setter
        public Builder channels(List<String> channels) {
            this.channels = Objects.requireNonNull(channels);
            return this;
        }
        public Builder channels(String... channels) {
            return channels(List.of(channels));
        }
        @CustomType.Setter
        public Builder logName(String logName) {
            this.logName = Objects.requireNonNull(logName);
            return this;
        }
        @CustomType.Setter
        public Builder minLevel(@Nullable String minLevel) {
            this.minLevel = minLevel;
            return this;
        }
        @CustomType.Setter
        public Builder redact(@Nullable Boolean redact) {
            this.redact = redact;
            return this;
        }
        public LogExportConfigGroup build() {
            final var o = new LogExportConfigGroup();
            o.channels = channels;
            o.logName = logName;
            o.minLevel = minLevel;
            o.redact = redact;
            return o;
        }
    }
}
