// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cockroach

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Information about the organization associated with the user's API key.
func GetOrganization(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetOrganizationResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetOrganizationResult
	err := ctx.Invoke("cockroach:index/getOrganization:getOrganization", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getOrganization.
type GetOrganizationResult struct {
	// Indicates when the organization was created.
	CreatedAt string `pulumi:"createdAt"`
	// Organization ID.
	Id string `pulumi:"id"`
	// A short ID used by CockroachDB Support.
	Label string `pulumi:"label"`
	// Name of the organization.
	Name string `pulumi:"name"`
}
