// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cockroach.Inputs
{

    public sealed class ClusterServerlessArgs : global::Pulumi.ResourceArgs
    {
        [Input("routingId")]
        public Input<string>? RoutingId { get; set; }

        [Input("spendLimit")]
        public Input<int>? SpendLimit { get; set; }

        [Input("usageLimits")]
        public Input<Inputs.ClusterServerlessUsageLimitsArgs>? UsageLimits { get; set; }

        public ClusterServerlessArgs()
        {
        }
        public static new ClusterServerlessArgs Empty => new ClusterServerlessArgs();
    }
}
