// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cockroach.Inputs
{

    public sealed class ClusterServerlessUsageLimitsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Maximum number of vCPUs that the cluster can use.
        /// </summary>
        [Input("provisionedVirtualCpus")]
        public Input<int>? ProvisionedVirtualCpus { get; set; }

        /// <summary>
        /// Maximum number of Request Units that the cluster can consume during the month.
        /// </summary>
        [Input("requestUnitLimit")]
        public Input<int>? RequestUnitLimit { get; set; }

        /// <summary>
        /// Maximum amount of storage (in MiB) that the cluster can have at any time during the month.
        /// </summary>
        [Input("storageMibLimit")]
        public Input<int>? StorageMibLimit { get; set; }

        public ClusterServerlessUsageLimitsArgs()
        {
        }
        public static new ClusterServerlessUsageLimitsArgs Empty => new ClusterServerlessUsageLimitsArgs();
    }
}
