// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cockroach.Inputs
{

    public sealed class PrivateEndpointServicesServicesMapGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("availabilityZoneIds")]
        private InputList<string>? _availabilityZoneIds;

        /// <summary>
        /// Availability Zone IDs of the private endpoint service. It is recommended, for cost optimization purposes, to create the private endpoint spanning these same availability zones. For more information, see data transfer cost information for your cloud provider.
        /// </summary>
        public InputList<string> AvailabilityZoneIds
        {
            get => _availabilityZoneIds ?? (_availabilityZoneIds = new InputList<string>());
            set => _availabilityZoneIds = value;
        }

        [Input("aws")]
        public Input<Inputs.PrivateEndpointServicesServicesMapAwsGetArgs>? Aws { get; set; }

        /// <summary>
        /// Cloud provider associated with this service.
        /// </summary>
        [Input("cloudProvider")]
        public Input<string>? CloudProvider { get; set; }

        /// <summary>
        /// Server side ID of the private endpoint connection.
        /// </summary>
        [Input("endpointServiceId")]
        public Input<string>? EndpointServiceId { get; set; }

        /// <summary>
        /// Name of the endpoint service.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Cloud provider region code associated with this service.
        /// </summary>
        [Input("regionName")]
        public Input<string>? RegionName { get; set; }

        /// <summary>
        /// Operation status of the service.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        public PrivateEndpointServicesServicesMapGetArgs()
        {
        }
        public static new PrivateEndpointServicesServicesMapGetArgs Empty => new PrivateEndpointServicesServicesMapGetArgs();
    }
}
