// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cockroach.Inputs
{

    public sealed class PrivateEndpointServicesServicesMapAwsArgs : global::Pulumi.ResourceArgs
    {
        [Input("availabilityZoneIds")]
        private InputList<string>? _availabilityZoneIds;

        /// <summary>
        /// AZ IDs users should create their VPCs in to minimize their cost.
        /// </summary>
        public InputList<string> AvailabilityZoneIds
        {
            get => _availabilityZoneIds ?? (_availabilityZoneIds = new InputList<string>());
            set => _availabilityZoneIds = value;
        }

        /// <summary>
        /// Server side ID of the PrivateLink connection.
        /// </summary>
        [Input("serviceId")]
        public Input<string>? ServiceId { get; set; }

        /// <summary>
        /// AWS service name used to create endpoints.
        /// </summary>
        [Input("serviceName")]
        public Input<string>? ServiceName { get; set; }

        public PrivateEndpointServicesServicesMapAwsArgs()
        {
        }
        public static new PrivateEndpointServicesServicesMapAwsArgs Empty => new PrivateEndpointServicesServicesMapAwsArgs();
    }
}
