// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Cockroach.Inputs
{

    public sealed class UserRoleGrantRoleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ID of the resource. Required if the resource_type is 'FOLDER' or 'CLUSTER'. It should be omitted otherwise.
        /// </summary>
        [Input("resourceId")]
        public Input<string>? ResourceId { get; set; }

        /// <summary>
        /// Type of resource. Allowed values are:
        ///   * ORGANIZATION
        ///   * CLUSTER
        ///   * FOLDER
        /// </summary>
        [Input("resourceType", required: true)]
        public Input<string> ResourceType { get; set; } = null!;

        /// <summary>
        /// Name of the role to grant. Allowed values are:
        ///   * BILLING_COORDINATOR
        ///   * ORG_ADMIN
        ///   * ORG_MEMBER
        ///   * CLUSTER_ADMIN
        ///   * CLUSTER_OPERATOR_WRITER
        ///   * CLUSTER_DEVELOPER
        ///   * CLUSTER_CREATOR
        ///   * FOLDER_ADMIN
        ///   * FOLDER_MOVER
        /// </summary>
        [Input("roleName", required: true)]
        public Input<string> RoleName { get; set; } = null!;

        public UserRoleGrantRoleArgs()
        {
        }
        public static new UserRoleGrantRoleArgs Empty => new UserRoleGrantRoleArgs();
    }
}
