// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages client CA certs.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@pulumiverse/cockroach";
 *
 * const config = new pulumi.Config();
 * // The X509 certificate in PEM format.
 * const clientCertificate = config.require("clientCertificate");
 * const prod = new cockroach.CaCert("prod", {
 *     clusterId: prodCockroachCluster.id,
 *     x509PemCert: clientCertificate,
 * });
 * ```
 *
 * ## Import
 *
 * format: <cluster id>
 *
 * ```sh
 * $ pulumi import cockroach:index/caCert:CaCert prod 1f69fdd2-600a-4cfc-a9ba-16995df0d77d
 * ```
 */
export class CaCert extends pulumi.CustomResource {
    /**
     * Get an existing CaCert resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CaCertState, opts?: pulumi.CustomResourceOptions): CaCert {
        return new CaCert(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cockroach:index/caCert:CaCert';

    /**
     * Returns true if the given object is an instance of CaCert.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CaCert {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CaCert.__pulumiType;
    }

    /**
     * Cluster ID.
     */
    public readonly clusterId!: pulumi.Output<string>;
    /**
     * Status of client CA certs on a cluster.
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    /**
     * X509 certificate in PEM format.
     */
    public readonly x509PemCert!: pulumi.Output<string>;

    /**
     * Create a CaCert resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CaCertArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CaCertArgs | CaCertState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CaCertState | undefined;
            resourceInputs["clusterId"] = state ? state.clusterId : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["x509PemCert"] = state ? state.x509PemCert : undefined;
        } else {
            const args = argsOrState as CaCertArgs | undefined;
            if ((!args || args.clusterId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'clusterId'");
            }
            if ((!args || args.x509PemCert === undefined) && !opts.urn) {
                throw new Error("Missing required property 'x509PemCert'");
            }
            resourceInputs["clusterId"] = args ? args.clusterId : undefined;
            resourceInputs["x509PemCert"] = args ? args.x509PemCert : undefined;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CaCert.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CaCert resources.
 */
export interface CaCertState {
    /**
     * Cluster ID.
     */
    clusterId?: pulumi.Input<string>;
    /**
     * Status of client CA certs on a cluster.
     */
    status?: pulumi.Input<string>;
    /**
     * X509 certificate in PEM format.
     */
    x509PemCert?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CaCert resource.
 */
export interface CaCertArgs {
    /**
     * Cluster ID.
     */
    clusterId: pulumi.Input<string>;
    /**
     * X509 certificate in PEM format.
     */
    x509PemCert: pulumi.Input<string>;
}
